"""empty message

Revision ID: 41ea5c6d6745
Revises: b40117511566
Create Date: 2023-02-02 20:11:59.124829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ea5c6d6745'
down_revision = 'b40117511566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', 'followedId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('follows', 'followerId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('likes', 'updated_at')
    op.drop_column('likes', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('likes', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('follows', 'followerId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('follows', 'followedId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
